version: '3.7'

services:
  app:
    build: .
    ports:
      - 3000
    environment:
      - "REDIS_HOST=cache"
      - "REDIS_PORT=6379"
    networks:
      - backend

  cache:
    image: redis:6
    ports:
      - 6379
    networks:
      - backend

  database:
    image: mysql:8
    environment:
      - "MYSQL_USER=svote"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
      - 3306
    networks:
      - backend

networks:
  backend:
    driver: bridge
