version: '3.7'

services:
  app:
    build: .
    ports:
      - 3000:3000
    environment:
      - "APP_ENV=production"
      - "REDIS_HOST=cache"
      - "REDIS_PORT=6379"
      - "DB_HOST=database"
      - "DB_PORT=5432"
    networks:
      - backend

  cache:
    image: redis:6
    ports:
      - 6379
    networks:
      - backend

  database:
    image: postgres:13.1
    environment:
      - "POSTGRES_USER=svote"
      - "POSTGRES_PASSWORD=your-db-password"
      - "POSTGRES_DB=svote"
    ports:
      - 5432
    networks:
      - backend

networks:
  backend:
    driver: bridge
